#include "global.h"

#define MODEL_NAME "western"
#define VOFX_VOICE "VOFX_PLAYER_MALE02"

void ScriptMain()
{
	srand(GetTickCount());

	MISC::SET_THIS_SCRIPT_CAN_BE_PAUSED(false);
	MISC::SET_THIS_SCRIPT_CAN_REMOVE_BLIPS_CREATED_BY_ANY_SCRIPT(true);

	while (SCRIPTS::IS_LOADING_SCREEN_VISIBLE()) {
		WAIT(0);
	}

	MISC::SET_GAME_PAUSED(true);

	SCRIPTS::_DISPLAY_LOADING_SCREENS(NULL, NULL, NULL, NULL, NULL, NULL);

	UINT64* ptr1 = getGlobalPtr(40 + 39);
	UINT64* ptr2 = getGlobalPtr(1935630 + 2);
	UINT64* ptr3 = getGlobalPtr(1946804 + 1);

	if (*ptr1 != joaat(MODEL_NAME) && *ptr2 != joaat(MODEL_NAME) || ENTITY::GET_ENTITY_MODEL(PLAYER::PLAYER_PED_ID()) != joaat(MODEL_NAME))
	{
		STREAMING::REQUEST_MODEL(joaat(MODEL_NAME), false);

		while (!STREAMING::HAS_MODEL_LOADED(joaat(MODEL_NAME)))
		{
			WAIT(0);
		}

		PLAYER::SET_PLAYER_MODEL(PLAYER::PLAYER_ID(), joaat(MODEL_NAME), true);

		STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(joaat(MODEL_NAME));

		*ptr1 = *ptr2 = joaat(MODEL_NAME);

		UINT64* playerPed = getGlobalPtr(35);

		*playerPed = PLAYER::GET_PLAYER_PED(PLAYER::GET_PLAYER_INDEX());
		PED::_SET_PED_ACTIVE_PLAYER_TYPE(PLAYER::PLAYER_PED_ID(), 0);

		*ptr3 = joaat("MPC_PLAYER_TYPE_MP_MALE");

		WAIT(3000);
	}

	SCRIPTS::SHUTDOWN_LOADING_SCREEN();

	while (SCRIPTS::IS_LOADING_SCREEN_VISIBLE() == true)
	{
		WAIT(0);
	}

	MISC::SET_GAME_PAUSED(false);
	GRAPHICS::ANIMPOSTFX_PLAY("RespawnWithHonor");

	PED::_SET_RANDOM_OUTFIT_VARIATION(PLAYER::PLAYER_PED_ID(), true);
	PED::_UPDATE_PED_VARIATION(PLAYER::PLAYER_PED_ID(), NULL, true, true, true, NULL);

	DECORATOR::DECOR_SET_BOOL(PLAYER::PLAYER_PED_ID(), "HAS_VOICE", false);
	PLAYER::_SET_PLAYER_RESET_FLAG(PLAYER::PLAYER_PED_ID(), PLAYER_RESET_FLAG_DISABLE_AMBIENT_GREETS, true);
	PLAYER::_SET_PLAYER_RESET_FLAG(PLAYER::PLAYER_PED_ID(), PLAYER_RESET_FLAG_DISABLE_PLAYER_GREET, true);
	PLAYER::_SET_PLAYER_RESET_FLAG(PLAYER::PLAYER_PED_ID(), PLAYER_RESET_FLAG_ENABLE_GREET_AUTO_REPLY, false);

	AUDIO::SET_AMBIENT_VOICE_NAME(PLAYER::PLAYER_PED_ID(), "SHARPSHOOTER");
	AUDIO::_SET_VOFX_PED_VOICE(PLAYER::PLAYER_PED_ID(), joaat(VOFX_VOICE));

	//Reset stats back to normal
	ATTRIBUTE::SET_ATTRIBUTE_POINTS(PLAYER::PLAYER_PED_ID(), PA_HEALTH, (int)reinterpret_cast<float&>(*getGlobalPtr(40 + 11095 + 12)));
	ATTRIBUTE::SET_ATTRIBUTE_POINTS(PLAYER::PLAYER_PED_ID(), PA_STAMINA, (int)reinterpret_cast<float&>(*getGlobalPtr(40 + 11095 + 12)));
	ATTRIBUTE::SET_ATTRIBUTE_POINTS(PLAYER::PLAYER_PED_ID(), PA_SPECIALABILITY, (int)reinterpret_cast<float&>(*getGlobalPtr(40 + 11095 + 12)));


	while (true)
	{
		*ptr1 = *ptr2 = joaat(MODEL_NAME);
		*ptr3 = joaat("MPC_PLAYER_TYPE_MP_MALE");

		PED::REMOVE_SHOP_ITEM_FROM_PED_BY_CATEGORY(PLAYER::PLAYER_PED_ID(), 0x3F1F01E5, 0, NULL);
		PED::REMOVE_SHOP_ITEM_FROM_PED_BY_CATEGORY(PLAYER::PLAYER_PED_ID(), 0xDA0E2C55, 0, NULL);
		PED::_UPDATE_PED_VARIATION(PLAYER::PLAYER_PED_ID(), NULL, true, true, true, NULL);

		AUDIO::SET_AMBIENT_VOICE_NAME(PLAYER::PLAYER_PED_ID(), "SHARPSHOOTER");
		AUDIO::_SET_VOFX_PED_VOICE(PLAYER::PLAYER_PED_ID(), joaat(VOFX_VOICE));

		MAP::SET_BLIP_NAME_TO_PLAYER_NAME(MAP::GET_MAIN_PLAYER_BLIP_ID(), PLAYER::PLAYER_ID());

		UpdatePedOutfit(PLAYER::PLAYER_PED_ID());

		WAIT(100);
	}
}
